name: ZAP baseline + full scan (parallel, GHCR image)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL objetivo (ej: http://demo.testfire.net)'
        required: false
        default: 'http://demo.testfire.net'
      allow_active_scan:
        description: 'Ejecutar full (active) scan? true/false'
        required: false
        default: 'true'

env:
  DEFAULT_TARGET: 'http://demo.testfire.net'
  ZAP_IMAGE: 'ghcr.io/zaproxy/zaproxy:stable'

jobs:
  baseline:
    name: ZAP Baseline (passive - safe)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set TARGET_URL
        run: echo "TARGET_URL=${{ github.event.inputs.target_url || env.DEFAULT_TARGET }}" >> $GITHUB_ENV

      - name: Create reports dir (writable)
        run: |
          mkdir -p zap_reports
          sudo chmod -R 777 zap_reports
      
      - name: Run ZAP baseline (passive)
        run: |
          docker run --rm -u 0:0 \
            -v "$GITHUB_WORKSPACE/zap_reports":/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t "${TARGET_URL}" -r baseline.html -J baseline.json -d

      - name: Upload baseline report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap_reports/baseline.*

  full-scan:
    name: ZAP Full Scan (active) - ENABLE MANUALLY
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.allow_active_scan == 'true' }}
    # No dependency: runs in parallel with baseline
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set TARGET_URL
        run: echo "TARGET_URL=${{ github.event.inputs.target_url || env.DEFAULT_TARGET }}" >> $GITHUB_ENV

      - name: Create reports dir (writable)
        run: |
          mkdir -p zap_reports
          sudo chmod -R 777 zap_reports
      
      - name: Run ZAP full scan (ACTIVE)
        run: |
          docker run --rm -u 0:0 \
            -v "$GITHUB_WORKSPACE/zap_reports":/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t "${TARGET_URL}" -r full.html -J full.json -I

      - name: Upload full scan report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report
          path: zap_reports/full.*

      - name: Fail if HIGH/CRITICAL alerts found
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          FILE="zap_reports/full.json"
          if [ ! -f "$FILE" ]; then
            echo "No se encontró full.json — saltando check."
            exit 0
          fi
          COUNT=$(jq '[.site[].alerts[] | select(.risk == "High" or .risk == "Critical")] | length' "$FILE")
          echo "High/Critical alerts found: $COUNT"
          if [ "$COUNT" -gt 0 ]; then
            echo "High/Critical alerts found - failing workflow."
            exit 1
          fi
